In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
x= list([1,2,3,4])
print(x)
arr = np.array(list(range(1, 1_000_001)))

In [22]:
print(arr[:100])

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [23]:
import time
result = []
start = time.time()
for num in arr:
    result.append(num**2)
result = np.array(result)
print("Time taken (slow) Python List:", time.time() - start)

start = time.time()
arr= arr**2
print("Time taken (fast) Num py:", time.time() - start)

Time taken (slow) Python List: 0.08780789375305176
Time taken (fast) Num py: 0.0009868144989013672


In [24]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)  # Output: [11 12 13 14 15]

[11 12 13 14 15]


In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2  # Element-wise addition
print(result)  # Output: [11 22 33]

[11 22 33]


In [26]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]

[[2 4 6]
 [5 7 9]]


In [28]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
print("Mean:", mean)
print("Standard Deviation:", std)
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
print("Normalized Data:")
print(normalized_data)

Mean: [20. 30. 40.]
Standard Deviation: [7.07106781 7.07106781 7.07106781]
Normalized Data:
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [40]:
# Simulating a dataset (5 samples, 3 features)
data = np.arange(5, 51, 5, dtype=int)

print(data) 
print(data.sum())
print(len(data))

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
print("Mean:", mean)
print("Standard Deviation:", std)
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
print("Normalized Data:")
print(normalized_data)

[ 5 10 15 20 25 30 35 40 45 50]
275
10
Mean: 27.5
Standard Deviation: 14.361406616345072
Normalized Data:
[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [47]:
arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print("mean:", np.mean(arr))
print("std:", np.std(arr))
print("var:", np.var(arr))
print("min:", np.min(arr))
print("max:", np.max(arr))
print("sum:", np.sum(arr))
print("prod:", np.prod(arr))
print("median:", np.median(arr))
print("50th percentile:", np.percentile(arr, 50))
print("argmin:", np.argmin(arr))
print("argmax:", np.argmax(arr))
print("corrcoef(arr1, arr2):")
print(np.corrcoef(arr1, arr2))
print("unique:", np.unique(arr))
print("diff:", np.diff(arr))
print("cumsum:", np.cumsum(arr))
print("linspace(0,10,5):", np.linspace(0, 10, 5))
print("log:", np.log(arr))
print("exp:", np.exp(arr))

mean: 3.0
std: 1.4142135623730951
var: 2.0
min: 1
max: 5
sum: 15
prod: 120
median: 3.0
50th percentile: 3.0
argmin: 0
argmax: 4
corrcoef(arr1, arr2):
[[ 1. -1.]
 [-1.  1.]]
unique: [1 2 3 4 5]
diff: [1 1 1 1]
cumsum: [ 1  3  6 10 15]
linspace(0,10,5): [ 0.   2.5  5.   7.5 10. ]
log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
