In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [2]:
flat = arr.flatten()

In [3]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
print(flat[3])

4


In [10]:
print(flat[3:6])

[4 5 6]


In [11]:
print(flat[:6])

[1 2 3 4 5 6]


In [12]:
print(flat[3:])

[ 4  5  6  7  8  9 10 11 12]


In [13]:
print(flat[3:13])

[ 4  5  6  7  8  9 10 11 12]


In [15]:
print(flat.size)

12


In [16]:
print(flat[::2])

[ 1  3  5  7  9 11]


In [17]:
print(flat[::3])

[ 1  4  7 10]


In [18]:
b = flat[2:6]

In [20]:
b

array([3, 4, 5, 6])

In [ ]:
b[0] = 99 # Modifying the main array 

In [23]:
flat

array([ 1,  2, 99,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
a = flat[1:5].copy()  # Creating a copy of the sliced array

In [25]:
a

array([ 2, 99,  4,  5])

In [26]:
a[0] = 55  # Modifying the copy does not affect the main array

In [28]:
a

array([55, 99,  4,  5])

In [29]:
flat

array([ 1,  2, 99,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
arr = np.array([1,23,42,24,532,12,34,65,78,89])

In [31]:
arr[[1,3,5,7]]

array([23, 24, 12, 65])

In [32]:
arr[arr > 30]

array([ 42, 532,  34,  65,  78,  89])

# Exercise

In [33]:
arr = np.array([[1,2,3],[6,7,8],[11,12,13]])

In [34]:
print(arr)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [35]:
print(arr.shape)

(3, 3)


In [36]:
arr = np.array([1.1,2.2,3.3,4.4,5.5])

In [38]:
arr.astype(np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [39]:
arr = np.array([1,2,3,4,5,6])

In [40]:
print(arr[arr%2==0])

[2 4 6]


In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [42]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.array(list(range(30,60)))
print(arr)

In [44]:
print(arr[arr>50])

[51 52 53 54 55 56 57 58 59]
