In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [3]:
arr[0]

array([1, 2, 3])

In [4]:
arr[1]

array([4, 5, 6])

In [12]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [13]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [14]:
arr[0][1]

np.int64(2)

In [15]:
arr[0,1]

np.int64(2)

In [27]:
arr[:3,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [42]:
arr3D= np.array([[[1, 2, 3],[4, 5, 6]],
                 [[7, 8, 9],[10, 11, 12]],
                 [[13, 14, 15],[16, 17, 18]]])

In [45]:
arr3D.shape

(3, 2, 3)

In [44]:
arr3D[1,1,1]

np.int64(11)

In [49]:
arr3D[:1,:1,:2]

array([[[1, 2]]])

In [46]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [50]:
arr3D[:1,:1,:2] = 0

In [51]:
arr3D

array([[[ 0,  0,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])