In [ ]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
arr2=np.array([[1,2,3],[4,5,6]])

In [6]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [10]:
np.eye(1,3)

array([[1., 0., 0.]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [22]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
myarr.shape

(4, 3)

In [25]:
myarr.size

12

In [26]:
myarr.dtype

dtype('int64')

In [27]:
myarr.ndim

2

In [30]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='float32')

In [31]:
myarr.dtype

dtype('float32')

In [32]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [34]:
n= myarr.astype('int32')

In [35]:
n.dtype

dtype('int32')

In [36]:
myarr.dtype

dtype('float32')

In [37]:
myarr.reshape(2,6)

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]], dtype=float32)

In [39]:
myarr.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
      dtype=float32)